// ignore_for_file: use_key_in_widget_constructors

import 'package:flutter/material.dart';
import 'package:google_nav_bar/google_nav_bar.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        bottomNavigationBar: Container(
          color: const Color.fromRGBO(188, 149, 115, 1),
          child: const Padding(
            padding: EdgeInsets.symmetric(horizontal: 90.0, vertical: 10.0),
            child: GNav(
              backgroundColor: Color.fromRGBO(188, 149, 115, 1),
              color: Colors.black87,
              activeColor: Colors.black,
              tabBackgroundColor: Colors.brown,
              gap: 8,
              padding: EdgeInsets.all(15),
              tabs: [
                GButton(
                  iconSize: 30,
                  icon: Icons.home_rounded,
                  text: 'Home',
                ),
                GButton(
                  iconSize: 30,
                  icon: Icons.folder_copy_rounded,
                  text: 'Recipes',
                ),
              ],
            ),
          ),
        ),
        body: ListView(children: [
          RecipeDoc(),
        ]),
      ),
    );
  }
}

class RecipeDoc extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: const ShapeDecoration(
            image: DecorationImage(
              image: AssetImage('assets/brown_pattern.png'),
              fit: BoxFit.cover,
            ),
            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 24,
                top: 113,
                child: Container(
                  width: 341,
                  height: 653,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFF6EF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: const [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 68,
                top: 193,
                child: SizedBox(
                  width: 138,
                  child: Text(
                    'Prep Time: -- min',
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 14,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 225,
                top: 193,
                child: SizedBox(
                  width: 138,
                  child: Text(
                    'Cook Time: -- min',
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 14,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 298,
                top: 692,
                child: Container(
                  width: 60,
                  height: 60,
                  decoration: const ShapeDecoration(
                    color: Color(0xFFAAB977),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 42,
                top: 493,
                child: SizedBox(
                  width: 142,
                  height: 200,
                  child: Text(
                    '1. Do this\n'
                    '2. Do that\n'
                    '3. Continue\n'
                    '4. More\n'
                    '5. Ok\n'
                    '6. Almost\n'
                    '7. One more time\n'
                    '8.Yay!',
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 18,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 38,
                top: 449,
                child: SizedBox(
                  width: 142,
                  height: 100,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Instructions',
                          style: TextStyle(
                            color: Color(0xFF3E4B3B),
                            fontSize: 20,
                            fontFamily: 'Georgia',
                            fontWeight: FontWeight.w700,
                            decoration: TextDecoration.underline,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: ':',
                          style: TextStyle(
                            color: Color(0xFF3E4B3B),
                            fontSize: 20,
                            fontFamily: 'Georgia',
                            fontWeight: FontWeight.w400,
                            decoration: TextDecoration.underline,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 226,
                child: Container(
                  width: 314,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFAAB977),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: const [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -16,
                top: 0,
                child: Container(
                  width: 424,
                  height: 86,
                  decoration: const BoxDecoration(
                    color: Color(0xFFBC9573),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 99,
                top: 140,
                child: Text(
                  'Recipe Name',
                  style: TextStyle(
                    color: Color(0xFF3E4B3B),
                    fontSize: 32,
                    fontFamily: 'Georgia',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 28,
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/BackButton.png'),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 46,
                top: 237,
                child: SizedBox(
                  width: 142,
                  height: 33,
                  child: Text(
                    'Ingredients:',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 20,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.underline,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 47,
                top: 280,
                child: SizedBox(
                  width: 142,
                  height: 133,
                  child: Text(
                    'blah\nblah\nblah\nblah\nblah',
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 18,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 195,
                top: 280,
                child: SizedBox(
                  width: 142,
                  height: 133,
                  child: Text(
                    'blah\nblah\nblah\nblah\nblah',
                    style: TextStyle(
                      color: Color(0xFF3E4B3B),
                      fontSize: 18,
                      fontFamily: 'Georgia',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 186,
                child: Container(
                  width: 19,
                  height: 31,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/ChefKnife.png'),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 203,
                top: 186,
                child: Container(
                  width: 19,
                  height: 31,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/FryingPan.png'),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 308,
                top: 677,
                child: Container(
                  width: 40,
                  height: 90,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/Notepad.png'),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 317,
                top: 28,
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/EditPencil.png'),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 170,
                top: 20,
                child: Container(
                  width: 50,
                  height: 50,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/image41.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
// void _navigate homePage(BuildContext context) {
//     Navigator.of(context).push(MaterialPageRoute(
//         builder: (context) => homePage(context))); ////CHANGE PAGE
//   }
